package com.amirghm.gerocery.utils.extentions

import android.view.View
import android.widget.ImageView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.databinding.BindingAdapter
import com.amirghm.gerocery.BuildConfig
import com.amirghm.gerocery.utils.imageloader.loadImage


/**
 *
 * Usage: Some useful function to define some useful parameters in the xml which generated by
 * data-binding process
 *
 */

@BindingAdapter("srcUrl")
fun ImageView.setSrcUrl(imageUrl: String?) {
    if (imageUrl.isNullOrEmpty())
        this.setImageDrawable(null)
    else
        loadImage("${BuildConfig.BASE_IMAGE_URL}$imageUrl", this)
}


/**
 * DataBinding adapter extension to set text placeholder.
 * if the textview text is null or empty then set place holder text
 *
 * @param description the String to set product description.
 *
 * */
@BindingAdapter("app:placeHolder")
fun TextView.setProductDescription(description: String) {
    if (text.isNullOrEmpty()) text = description
}

/**
 * With this binding function the view pop back to previous state/page
 */
@BindingAdapter("navigateUpOnClick")
fun View.navigateUp(isEnabled: Boolean = false) {
    if (isEnabled) setOnClickListener {
        context?.let {
            (it as AppCompatActivity).onBackPressed()
        }
    }
}
